class PlayLocalization {
  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'userProfile': 'My Profile',
      'adventure': 'Adventure',
      'arcade': 'Arcade',
      'favoriteBadges': 'Favorite Badges',
      'totalBadges': 'Total\nBadges',
      'stagesCleared': 'Stages\nCleared',
      'level': 'Level',
      'nickname': 'Nickname',
      'birthday': 'Birthday',
      'email': 'Email',
      'password': 'Password',
      'logout': 'Logout',
      'logoutButton': 'Logout',
      'change': 'Change',
      'accountRemoval': 'Account Removal',
      'accountRemovalDescription': 'Deleting your account will permanently erase all of your account data, including your game rewards and game progress.',
      'changeNickname': 'Change Nickname',
      'changePassword': 'Change Password',
      'newNickname': 'New Nickname',
      'cancel': 'Cancel',
      'save': 'Save',
      'show': 'Show',
      'hide': 'Hide',
      'confirmAccountDeletion': 'Confirm Account Deletion',
      'accountDeletionWarning': 'Are you sure you want to delete your account? This action cannot be undone.',
      'delete': 'Delete',
      'errorFetchingProfile': 'Error fetching user profile: ',
      'errorUpdatingNickname': 'Error updating nickname: ',
      'errorDeletingAccount': 'Error deleting account: ',
      'error': 'Error: ',
      'changeAvatar': 'Change Avatar',
      'changeBanner': 'Change Banner',
      'changeFavoriteBadges': 'Change Favorite Badges',
      'register': 'Register Account',
      'registerButton': 'Register',
    },
    'fil': {
      'userProfile': 'Aking Profile',
      'adventure': 'Pakikipagsapalaran',
      'arcade': 'Arkada',
      'favoriteBadges': 'Paboritong Mga Badge',
      'totalBadges': 'Kabuuang\nBadge',
      'stagesCleared': 'Mga Stage \nna na-Clear',
      'level': 'Level',
      'nickname': 'Nickname',
      'birthday': 'Kaarawan',
      'email': 'Email',
      'password': 'Password',
      'logout': 'Logout',
      'logoutButton': 'Mag-Logout',
      'change': 'Baguhin',
      'accountRemoval': 'Pag-delete ng Account',
      'accountRemovalDescription': 'Ang pag-delete ng iyong account ay permanenteng buburahin ang lahat ng iyong data sa account, kabilang ang iyong mga gantimpala sa laro at progreso sa laro.',
      'changeNickname': 'Baguhin ang Palayaw',
      'changePassword': 'Baguhin ang Password',
      'newNickname': 'Bagong Palayaw',
      'cancel': 'Kanselahin',
      'save': 'I-save',
      'show': 'Ipakita',
      'hide': 'Itago',
      'confirmAccountDeletion': 'Kumpirmahin ang Pagkakabura ng Account',
      'accountDeletionWarning': 'Sigurado ka bang gusto mong burahin ang iyong account? Ang aksyong ito ay hindi na maaaring balikan.',
      'delete': 'I-delete ang Account',
      'errorFetchingProfile': 'Error sa pagkuha ng profile ng user: ',
      'errorUpdatingNickname': 'Error sa pag-update ng palayaw: ',
      'errorDeletingAccount': 'Error sa pagbura ng account: ',
      'error': 'Error: ',
      'changeAvatar': 'Baguhin ang Avatar',
      'changeBanner': 'Baguhin ang Banner',
      'changeFavoriteBadges': 'Baguhin ang Mga\nPaboritong Badge',
      'register': 'Magparehistro ng Account',
      'registerButton': 'Magparehistro',
    },
  };

  static String translate(String key, String language) {
    return _localizedValues[language]?[key] ?? key;
  }
}