// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyAJXFiGBw7TWk4xH165Pl0irixh1BCGweg",
    authDomain: "handabatamae.firebaseapp.com",
    projectId: "handabatamae",
    storageBucket: "handabatamae.appspot.com",
    messagingSenderId: "939684811739",
    appId: "1:939684811739:web:993c8968b12583ba300dfe",
    measurementId: "G-S4X6BQS7ZS"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM_t1eGn4B6-__KlfM5pbo-4-IGUxmW7o',
    appId: '1:939684811739:android:b4c08ad000963026300dfe',
    messagingSenderId: '939684811739',
    projectId: 'handabatamae',
    storageBucket: 'handabatamae.appspot.com',
  );
}