class BadgeDescriptionLocalization {
  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      '0': 'Obtain three stars at Stage 1 (Normal) of Quake Quest.',
      '1': 'Obtain three stars at Stage 1 (Hard) of Quake Quest.',
      '2': 'Obtain three stars at Stage 2 (Normal) of Quake Quest.',
      '3': 'Obtain three stars at Stage 2 (Hard) of Quake Quest.',
      '4': 'Obtain three stars at Stage 3 (Normal) of Quake Quest.',
      '5': 'Obtain three stars at Stage 3 (Hard) of Quake Quest.',
      '6': 'Obtain three stars at Stage 4 (Normal) of Quake Quest.',
      '7': 'Obtain three stars at Stage 4 (Hard) of Quake Quest.',
      '8': 'Obtain three stars at Stage 5 (Normal) of Quake Quest.',
      '9': 'Obtain three stars at Stage 5 (Hard) of Quake Quest.',
      '10': 'Obtain three stars at Stage 6 (Normal) of Quake Quest.',
      '11': 'Obtain three stars at Stage 6 (Hard) of Quake Quest.',
      '12': 'Obtain three stars at Stage 7 (Normal) of Quake Quest.',
      '13': 'Obtain three stars at Stage 7 (Hard) of Quake Quest.',
      '14': 'Clear all normal stages of Quake Quest.',
      '15': 'Clear all hard stages of Quake Quest.',
      '16': 'Obtain three stars on all normal stages of Quake Quest.',
      '17': 'Obtain three stars on all hard stages of Quake Quest.',
      '18': 'Obtain three stars at Stage 1 (Normal) of Storm Quest.',
      '19': 'Obtain three stars at Stage 1 (Hard) of Storm Quest.',
      '20': 'Obtain three stars at Stage 2 (Normal) of Storm Quest.',
      '21': 'Obtain three stars at Stage 2 (Hard) of Storm Quest.',
      '22': 'Obtain three stars at Stage 3 (Normal) of Storm Quest.',
      '23': 'Obtain three stars at Stage 3 (Hard) of Storm Quest.',
      '24': 'Obtain three stars at Stage 4 (Normal) of Storm Quest.',
      '25': 'Obtain three stars at Stage 4 (Hard) of Storm Quest.',
      '26': 'Obtain three stars at Stage 5 (Normal) of Storm Quest.',
      '27': 'Obtain three stars at Stage 5 (Hard) of Storm Quest.',
      '28': 'Obtain three stars at Stage 6 (Normal) of Storm Quest.',
      '29': 'Obtain three stars at Stage 6 (Hard) of Storm Quest.',
      '30': 'Obtain three stars at Stage 7 (Normal) of Storm Quest.',
      '31': 'Obtain three stars at Stage 7 (Hard) of Storm Quest.',
      '32': 'Clear all normal stages of Storm Quest.',
      '33': 'Clear all hard stages of Storm Quest.',
      '34': 'Obtain three stars on all normal stages of Storm Quest.',
      '35': 'Obtain three stars on all hard stages of Storm Quest.',
      '36': 'Achieve a record of 2 minutes or less on any arcade game.',
      '37': 'Achieve a perfect score on any arcade game.',
      '38': 'Achieve a streak of 15 correct answers on any arcade game.',
      '39': 'Achieve a speed of 15 seconds or less on any arcade game.',
      '40': 'Obtain three stars at Stage 1 (Normal) of Volcano Quest.',
      '41': 'Obtain three stars at Stage 1 (Hard) of Volcano Quest.',
      '42': 'Obtain three stars at Stage 2 (Normal) of Volcano Quest.',
      '43': 'Obtain three stars at Stage 2 (Hard) of Volcano Quest.',
      '44': 'Obtain three stars at Stage 3 (Normal) of Volcano Quest.',
      '45': 'Obtain three stars at Stage 3 (Hard) of Volcano Quest.',
      '46': 'Obtain three stars at Stage 4 (Normal) of Volcano Quest.',
      '47': 'Obtain three stars at Stage 4 (Hard) of Volcano Quest.',
      '48': 'Obtain three stars at Stage 5 (Normal) of Volcano Quest.',
      '49': 'Obtain three stars at Stage 5 (Hard) of Volcano Quest.',
      '50': 'Obtain three stars at Stage 6 (Normal) of Volcano Quest.',
      '51': 'Obtain three stars at Stage 6 (Hard) of Volcano Quest.',
      '52': 'Obtain three stars at Stage 7 (Normal) of Volcano Quest.',
      '53': 'Obtain three stars at Stage 7 (Hard) of Volcano Quest.',
      '54': 'Clear all normal stages of Volcano Quest.',
      '55': 'Clear all hard stages of Volcano Quest.',
      '56': 'Obtain three stars on all normal stages of Volcano Quest.',
      '57': 'Obtain three stars on all hard stages of Volcano Quest.',
      '58': 'Obtain three stars at Stage 1 (Normal) of Drought Quest.',
      '59': 'Obtain three stars at Stage 1 (Hard) of Drought Quest.',
      '60': 'Obtain three stars at Stage 2 (Normal) of Drought Quest.',
      '61': 'Obtain three stars at Stage 2 (Hard) of Drought Quest.',
      '62': 'Obtain three stars at Stage 3 (Normal) of Drought Quest.',
      '63': 'Obtain three stars at Stage 3 (Hard) of Drought Quest.',
      '64': 'Obtain three stars at Stage 4 (Normal) of Drought Quest.',
      '65': 'Obtain three stars at Stage 4 (Hard) of Drought Quest.',
      '66': 'Obtain three stars at Stage 5 (Normal) of Drought Quest.',
      '67': 'Obtain three stars at Stage 5 (Hard) of Drought Quest.',
      '68': 'Obtain three stars at Stage 6 (Normal) of Drought Quest.',
      '69': 'Obtain three stars at Stage 6 (Hard) of Drought Quest.',
      '70': 'Obtain three stars at Stage 7 (Normal) of Drought Quest.',
      '71': 'Obtain three stars at Stage 7 (Hard) of Drought Quest.',
      '72': 'Clear all normal stages of Drought Quest.',
      '73': 'Clear all hard stages of Drought Quest.',
      '74': 'Obtain three stars on all normal stages of Drought Quest.',
      '75': 'Obtain three stars on all hard stages of Drought Quest.',
      '76': 'Obtain three stars at Stage 1 (Normal) of Tsunami Quest.',
      '77': 'Obtain three stars at Stage 1 (Hard) of Tsunami Quest.',
      '78': 'Obtain three stars at Stage 2 (Normal) of Tsunami Quest.',
      '79': 'Obtain three stars at Stage 2 (Hard) of Tsunami Quest.',
      '80': 'Obtain three stars at Stage 3 (Normal) of Tsunami Quest.',
      '81': 'Obtain three stars at Stage 3 (Hard) of Tsunami Quest.',
      '82': 'Obtain three stars at Stage 4 (Normal) of Tsunami Quest.',
      '83': 'Obtain three stars at Stage 4 (Hard) of Tsunami Quest.',
      '84': 'Obtain three stars at Stage 5 (Normal) of Tsunami Quest.',
      '85': 'Obtain three stars at Stage 5 (Hard) of Tsunami Quest.',
      '86': 'Obtain three stars at Stage 6 (Normal) of Tsunami Quest.',
      '87': 'Obtain three stars at Stage 6 (Hard) of Tsunami Quest.',
      '88': 'Obtain three stars at Stage 7 (Normal) of Tsunami Quest.',
      '89': 'Obtain three stars at Stage 7 (Hard) of Tsunami Quest.',
      '90': 'Clear all normal stages of Tsunami Quest.',
      '91': 'Clear all hard stages of Tsunami Quest.',
      '92': 'Obtain three stars on all normal stages of Tsunami Quest.',
      '93': 'Obtain three stars on all hard stages of Tsunami Quest.',
      '94': 'Obtain three stars at Stage 1 (Normal) of Flood Quest.',
      '95': 'Obtain three stars at Stage 1 (Hard) of Flood Quest.',
      '96': 'Obtain three stars at Stage 2 (Normal) of Flood Quest.',
      '97': 'Obtain three stars at Stage 2 (Hard) of Flood Quest.',
      '98': 'Obtain three stars at Stage 3 (Normal) of Flood Quest.',
      '99': 'Obtain three stars at Stage 3 (Hard) of Flood Quest.',
      '100': 'Obtain three stars at Stage 4 (Normal) of Flood Quest.',
      '101': 'Obtain three stars at Stage 4 (Hard) of Flood Quest.',
      '102': 'Obtain three stars at Stage 5 (Normal) of Flood Quest.',
      '103': 'Obtain three stars at Stage 5 (Hard) of Flood Quest.',
      '104': 'Obtain three stars at Stage 6 (Normal) of Flood Quest.',
      '105': 'Obtain three stars at Stage 6 (Hard) of Flood Quest.',
      '106': 'Obtain three stars at Stage 7 (Normal) of Flood Quest.',
      '107': 'Obtain three stars at Stage 7 (Hard) of Flood Quest.',
      '108': 'Clear all normal stages of Flood Quest.',
      '109': 'Clear all hard stages of Flood Quest.',
      '110': 'Obtain three stars on all normal stages of Flood Quest.',
      '111': 'Obtain three stars on all hard stages of Flood Quest.',
    },
    'fil': {
      '0': 'Magkamit ng tatlong bituin sa Stage 1 (Normal) ng Quake Quest.',
      '1': 'Magkamit ng tatlong bituin sa Stage 1 (Hard) ng Quake Quest.',
      '2': 'Magkamit ng tatlong bituin sa Stage 2 (Normal) ng Quake Quest.',
      '3': 'Magkamit ng tatlong bituin sa Stage 2 (Hard) ng Quake Quest.',
      '4': 'Magkamit ng tatlong bituin sa Stage 3 (Normal) ng Quake Quest.',
      '5': 'Magkamit ng tatlong bituin sa Stage 3 (Hard) ng Quake Quest.',
      '6': 'Magkamit ng tatlong bituin sa Stage 4 (Normal) ng Quake Quest.',
      '7': 'Magkamit ng tatlong bituin sa Stage 4 (Hard) ng Quake Quest.',
      '8': 'Magkamit ng tatlong bituin sa Stage 5 (Normal) ng Quake Quest.',
      '9': 'Magkamit ng tatlong bituin sa Stage 5 (Hard) ng Quake Quest.',
      '10': 'Magkamit ng tatlong bituin sa Stage 6 (Normal) ng Quake Quest.',
      '11': 'Magkamit ng tatlong bituin sa Stage 6 (Hard) ng Quake Quest.',
      '12': 'Magkamit ng tatlong bituin sa Stage 7 (Normal) ng Quake Quest.',
      '13': 'Magkamit ng tatlong bituin sa Stage 7 (Hard) ng Quake Quest.',
      '14': 'I-clear ang lahat ng mga normal stage ng Quake Quest.',
      '15': 'I-clear ang lahat ng mga hard stage ng Quake Quest.',
      '16': 'Magkamit ng tatlong bituin sa lahat ng mga normal stage ng Quake Quest.',
      '17': 'Magkamit ng tatlong bituin sa lahat ng mga hard stage ng Quake Quest.',
      '18': 'Magkamit ng tatlong bituin sa Stage 1 (Normal) ng Storm Quest.',
      '19': 'Magkamit ng tatlong bituin sa Stage 1 (Hard) ng Storm Quest.',
      '20': 'Magkamit ng tatlong bituin sa Stage 2 (Normal) ng Storm Quest.',
      '21': 'Magkamit ng tatlong bituin sa Stage 2 (Hard) ng Storm Quest.',
      '22': 'Magkamit ng tatlong bituin sa Stage 3 (Normal) ng Storm Quest.',
      '23': 'Magkamit ng tatlong bituin sa Stage 3 (Hard) ng Storm Quest.',
      '24': 'Magkamit ng tatlong bituin sa Stage 4 (Normal) ng Storm Quest.',
      '25': 'Magkamit ng tatlong bituin sa Stage 4 (Hard) ng Storm Quest.',
      '26': 'Magkamit ng tatlong bituin sa Stage 5 (Normal) ng Storm Quest.',
      '27': 'Magkamit ng tatlong bituin sa Stage 5 (Hard) ng Storm Quest.',
      '28': 'Magkamit ng tatlong bituin sa Stage 6 (Normal) ng Storm Quest.',
      '29': 'Magkamit ng tatlong bituin sa Stage 6 (Hard) ng Storm Quest.',
      '30': 'Magkamit ng tatlong bituin sa Stage 7 (Normal) ng Storm Quest.',
      '31': 'Magkamit ng tatlong bituin sa Stage 7 (Hard) ng Storm Quest.',
      '32': 'I-clear ang lahat ng mga normal stage ng Storm Quest.',
      '33': 'I-clear ang lahat ng mga hard stage ng Storm Quest.',
      '34': 'Magkamit ng tatlong bituin sa lahat ng mga normal stage ng Storm Quest.',
      '35': 'Magkamit ng tatlong bituin sa lahat ng mga hard stage ng Storm Quest.',
      '36': 'Magkamit ng record na 2 minuto o mas mababa sa anumang arcade game.',
      '37': 'Magkamit ng perpektong marka sa anumang arcade game.',
      '38': 'Magkamit ng streak na 15 na tamang sagot sa anumang arcade game.',
      '39': 'Magkamit ng bilis na 15 segundo o mas mababa sa anumang arcade game.',
      '40': 'Magkamit ng tatlong bituin sa Stage 1 (Normal) ng Volcano Quest.',
      '41': 'Magkamit ng tatlong bituin sa Stage 1 (Hard) ng Volcano Quest.',
      '42': 'Magkamit ng tatlong bituin sa Stage 2 (Normal) ng Volcano Quest.',
      '43': 'Magkamit ng tatlong bituin sa Stage 2 (Hard) ng Volcano Quest.',
      '44': 'Magkamit ng tatlong bituin sa Stage 3 (Normal) ng Volcano Quest.',
      '45': 'Magkamit ng tatlong bituin sa Stage 3 (Hard) ng Volcano Quest.',
      '46': 'Magkamit ng tatlong bituin sa Stage 4 (Normal) ng Volcano Quest.',
      '47': 'Magkamit ng tatlong bituin sa Stage 4 (Hard) ng Volcano Quest.',
      '48': 'Magkamit ng tatlong bituin sa Stage 5 (Normal) ng Volcano Quest.',
      '49': 'Magkamit ng tatlong bituin sa Stage 5 (Hard) ng Volcano Quest.',
      '50': 'Magkamit ng tatlong bituin sa Stage 6 (Normal) ng Volcano Quest.',
      '51': 'Magkamit ng tatlong bituin sa Stage 6 (Hard) ng Volcano Quest.',
      '52': 'Magkamit ng tatlong bituin sa Stage 7 (Normal) ng Volcano Quest.',
      '53': 'Magkamit ng tatlong bituin sa Stage 7 (Hard) ng Volcano Quest.',
      '54': 'I-clear ang lahat ng mga normal stage ng Volcano Quest.',
      '55': 'I-clear ang lahat ng mga hard stage ng Volcano Quest.',
      '56': 'Magkamit ng tatlong bituin sa lahat ng mga normal stage ng Volcano Quest.',
      '57': 'Magkamit ng tatlong bituin sa lahat ng mga hard stage ng Volcano Quest.',
      '58': 'Magkamit ng tatlong bituin sa Stage 1 (Normal) ng Drought Quest.',
      '59': 'Magkamit ng tatlong bituin sa Stage 1 (Hard) ng Drought Quest.',
      '60': 'Magkamit ng tatlong bituin sa Stage 2 (Normal) ng Drought Quest.',
      '61': 'Magkamit ng tatlong bituin sa Stage 2 (Hard) ng Drought Quest.',
      '62': 'Magkamit ng tatlong bituin sa Stage 3 (Normal) ng Drought Quest.',
      '63': 'Magkamit ng tatlong bituin sa Stage 3 (Hard) ng Drought Quest.',
      '64': 'Magkamit ng tatlong bituin sa Stage 4 (Normal) ng Drought Quest.',
      '65': 'Magkamit ng tatlong bituin sa Stage 4 (Hard) ng Drought Quest.',
      '66': 'Magkamit ng tatlong bituin sa Stage 5 (Normal) ng Drought Quest.',
      '67': 'Magkamit ng tatlong bituin sa Stage 5 (Hard) ng Drought Quest.',
      '68': 'Magkamit ng tatlong bituin sa Stage 6 (Normal) ng Drought Quest.',
      '69': 'Magkamit ng tatlong bituin sa Stage 6 (Hard) ng Drought Quest.',
      '70': 'Magkamit ng tatlong bituin sa Stage 7 (Normal) ng Drought Quest.',
      '71': 'Magkamit ng tatlong bituin sa Stage 7 (Hard) ng Drought Quest.',
      '72': 'I-clear ang lahat ng mga normal stage ng Drought Quest.',
      '73': 'I-clear ang lahat ng mga hard stage ng Drought Quest.',
      '74': 'Magkamit ng tatlong bituin sa lahat ng mga normal stage ng Drought Quest.',
      '75': 'Magkamit ng tatlong bituin sa lahat ng mga hard stage ng Drought Quest.',
      '76': 'Magkamit ng tatlong bituin sa Stage 1 (Normal) ng Tsunami Quest.',
      '77': 'Magkamit ng tatlong bituin sa Stage 1 (Hard) ng Tsunami Quest.',
      '78': 'Magkamit ng tatlong bituin sa Stage 2 (Normal) ng Tsunami Quest.',
      '79': 'Magkamit ng tatlong bituin sa Stage 2 (Hard) ng Tsunami Quest.',
      '80': 'Magkamit ng tatlong bituin sa Stage 3 (Normal) ng Tsunami Quest.',
      '81': 'Magkamit ng tatlong bituin sa Stage 3 (Hard) ng Tsunami Quest.',
      '82': 'Magkamit ng tatlong bituin sa Stage 4 (Normal) ng Tsunami Quest.',
      '83': 'Magkamit ng tatlong bituin sa Stage 4 (Hard) ng Tsunami Quest.',
      '84': 'Magkamit ng tatlong bituin sa Stage 5 (Normal) ng Tsunami Quest.',
      '85': 'Magkamit ng tatlong bituin sa Stage 5 (Hard) ng Tsunami Quest.',
      '86': 'Magkamit ng tatlong bituin sa Stage 6 (Normal) ng Tsunami Quest.',
      '87': 'Magkamit ng tatlong bituin sa Stage 6 (Hard) ng Tsunami Quest.',
      '88': 'Magkamit ng tatlong bituin sa Stage 7 (Normal) ng Tsunami Quest.',
      '89': 'Magkamit ng tatlong bituin sa Stage 7 (Hard) ng Tsunami Quest.',
      '90': 'I-clear ang lahat ng mga normal stage ng Tsunami Quest.',
      '91': 'I-clear ang lahat ng mga hard stage ng Tsunami Quest.',
      '92': 'Magkamit ng tatlong bituin sa lahat ng mga normal stage ng Tsunami Quest.',
      '93': 'Magkamit ng tatlong bituin sa lahat ng mga hard stage ng Tsunami Quest.',
      '94': 'Magkamit ng tatlong bituin sa Stage 1 (Normal) ng Flood Quest.',
      '95': 'Magkamit ng tatlong bituin sa Stage 1 (Hard) ng Flood Quest.',
      '96': 'Magkamit ng tatlong bituin sa Stage 2 (Normal) ng Flood Quest.',
      '97': 'Magkamit ng tatlong bituin sa Stage 2 (Hard) ng Flood Quest.',
      '98': 'Magkamit ng tatlong bituin sa Stage 3 (Normal) ng Flood Quest.',
      '99': 'Magkamit ng tatlong bituin sa Stage 3 (Hard) ng Flood Quest.',
      '100': 'Magkamit ng tatlong bituin sa Stage 4 (Normal) ng Flood Quest.',
      '101': 'Magkamit ng tatlong bituin sa Stage 4 (Hard) ng Flood Quest.',
      '102': 'Magkamit ng tatlong bituin sa Stage 5 (Normal) ng Flood Quest.',
      '103': 'Magkamit ng tatlong bituin sa Stage 5 (Hard) ng Flood Quest.',
      '104': 'Magkamit ng tatlong bituin sa Stage 6 (Normal) ng Flood Quest.',
      '105': 'Magkamit ng tatlong bituin sa Stage 6 (Hard) ng Flood Quest.',
      '106': 'Magkamit ng tatlong bituin sa Stage 7 (Normal) ng Flood Quest.',
      '107': 'Magkamit ng tatlong bituin sa Stage 7 (Hard) ng Flood Quest.',
      '108': 'I-clear ang lahat ng mga normal stage ng Flood Quest.',
      '109': 'I-clear ang lahat ng mga hard stage ng Flood Quest.',
      '110': 'Magkamit ng tatlong bituin sa lahat ng mga normal stage ng Flood Quest.',
      '111': 'Magkamit ng tatlong bituin sa lahat ng mga hard stage ng Flood Quest.',
    },
  };

  static String translate(String id, String language) {
    return _localizedValues[language]?[id] ?? 'No description available.';
  }

  static String getLocalizedDescription(int badgeId, [String language = 'en']) {
    return translate(badgeId.toString(), language);
  }
}